/**
 * Export pre-colored character sprites to PNG files.
 *
 * Generates 6 PNG files (one per palette) in
 * webview-ui/public/assets/characters/. Each PNG is 112×96:
 *   - 7 frames horizontally (16px each) = 112px wide
 *   - 3 direction rows vertically (32px each) = 96px tall
 *     Row 0 = down, Row 1 = up, Row 2 = right
 *
 * Frame order per row: walk1, walk2, walk3, type1, type2, read1, read2
 *
 * Colors are baked in from the palettes — no template swapping at runtime.
 * Left-facing sprites are still generated by flipping right at runtime.
 *
 * Run: npx tsx scripts/export-characters.ts
 */

import * as fs from 'fs'
import * as path from 'path'
import { PNG } from 'pngjs'

// ─────────────────────────────────────────────────────────────────────
// Sprite dimensions
// ─────────────────────────────────────────────────────────────────────

const FRAME_W = 16
const FRAME_H = 32
const SPRITE_H = 24 // actual template height — bottom-aligned in frame
const FRAMES_PER_ROW = 7
const DIRECTIONS = ['down', 'up', 'right'] as const

// ─────────────────────────────────────────────────────────────────────
// Palettes — mirrors webview-ui/src/office/sprites/defaultCharacters.ts
// ─────────────────────────────────────────────────────────────────────

const CHARACTER_PALETTES = [
  { shirt: '#4169E1', skin: '#FDBCB4', pants: '#2C3E50' },
  { shirt: '#DC143C', skin: '#FDBCB4', pants: '#2C3E50' },
  { shirt: '#32CD32', skin: '#C68642', pants: '#2C3E50' },
  { shirt: '#9370DB', skin: '#8D5524', pants: '#2C3E50' },
  { shirt: '#FF8C00', skin: '#FDBCB4', pants: '#2C3E50' },
  { shirt: '#20B2AA', skin: '#C68642', pants: '#2C3E50' },
]

// ─────────────────────────────────────────────────────────────────────
// Sprite generation — same logic as defaultCharacters.ts
// ─────────────────────────────────────────────────────────────────────

type SpriteData = string[][]

function emptySprite(): SpriteData {
  return Array(SPRITE_H).fill(null).map(() => Array(FRAME_W).fill(''))
}

function createCharacterWalkDown(shirt: string, skin: string, pants: string): SpriteData {
  const s = emptySprite()
  for (let y = 2; y < 8; y++) for (let x = 5; x < 11; x++) s[y][x] = skin
  s[4][6] = '#000000'; s[4][9] = '#000000'
  for (let y = 8; y < 16; y++) for (let x = 4; x < 12; x++) s[y][x] = shirt
  for (let y = 16; y < 24; y++) {
    for (let x = 5; x < 7; x++) s[y][x] = pants
    for (let x = 9; x < 11; x++) s[y][x] = pants
  }
  return s
}

function createCharacterWalkFrame2(shirt: string, skin: string, pants: string): SpriteData {
  const s = emptySprite()
  for (let y = 2; y < 8; y++) for (let x = 5; x < 11; x++) s[y][x] = skin
  s[4][6] = '#000000'; s[4][9] = '#000000'
  for (let y = 8; y < 16; y++) for (let x = 4; x < 12; x++) s[y][x] = shirt
  for (let y = 16; y < 24; y++) {
    for (let x = 3; x < 5; x++) s[y][x] = pants
    for (let x = 9; x < 11; x++) s[y][x] = pants
  }
  return s
}

function createCharacterWalkFrame4(shirt: string, skin: string, pants: string): SpriteData {
  const s = emptySprite()
  for (let y = 2; y < 8; y++) for (let x = 5; x < 11; x++) s[y][x] = skin
  s[4][6] = '#000000'; s[4][9] = '#000000'
  for (let y = 8; y < 16; y++) for (let x = 4; x < 12; x++) s[y][x] = shirt
  for (let y = 16; y < 24; y++) {
    for (let x = 5; x < 7; x++) s[y][x] = pants
    for (let x = 11; x < 13; x++) s[y][x] = pants
  }
  return s
}

function createCharacterTypingFrame1(shirt: string, skin: string, pants: string): SpriteData {
  const s = emptySprite()
  for (let y = 2; y < 8; y++) for (let x = 5; x < 11; x++) s[y][x] = skin
  s[4][6] = '#000000'; s[4][9] = '#000000'
  for (let y = 8; y < 16; y++) for (let x = 4; x < 12; x++) s[y][x] = shirt
  s[10][2] = skin; s[11][2] = skin; s[10][13] = skin; s[11][13] = skin
  for (let y = 16; y < 24; y++) {
    for (let x = 5; x < 7; x++) s[y][x] = pants
    for (let x = 9; x < 11; x++) s[y][x] = pants
  }
  return s
}

function createCharacterTypingFrame2(shirt: string, skin: string, pants: string): SpriteData {
  const s = emptySprite()
  for (let y = 2; y < 8; y++) for (let x = 5; x < 11; x++) s[y][x] = skin
  s[4][6] = '#000000'; s[4][9] = '#000000'
  for (let y = 8; y < 16; y++) for (let x = 4; x < 12; x++) s[y][x] = shirt
  s[12][2] = skin; s[13][2] = skin; s[12][13] = skin; s[13][13] = skin
  for (let y = 16; y < 24; y++) {
    for (let x = 5; x < 7; x++) s[y][x] = pants
    for (let x = 9; x < 11; x++) s[y][x] = pants
  }
  return s
}

/** Parse a hex color string like '#RRGGBB' into [r, g, b] */
function hexToRgb(hex: string): [number, number, number] {
  const r = parseInt(hex.slice(1, 3), 16)
  const g = parseInt(hex.slice(3, 5), 16)
  const b = parseInt(hex.slice(5, 7), 16)
  return [r, g, b]
}

// ─────────────────────────────────────────────────────────────────────
// PNG generation
// ─────────────────────────────────────────────────────────────────────

/**
 * For each direction, produce 7 frames:
 *   walk1 (standing), walk2 (left-step), walk3 (right-step),
 *   type1, type2, read1, read2
 *
 * All directions currently share the same base sprites (squad-pod's
 * procedural sprites don't have separate up/right templates yet).
 * Left-facing is handled at runtime by flipping right.
 */
function buildCharacterPng(paletteIndex: number): Buffer {
  const pal = CHARACTER_PALETTES[paletteIndex]
  const width = FRAME_W * FRAMES_PER_ROW  // 112
  const height = FRAME_H * DIRECTIONS.length  // 96
  const png = new PNG({ width, height })

  const padTop = FRAME_H - SPRITE_H // 8px transparent padding at top of each frame

  // Generate the 7 frames (same for all directions in current sprite set)
  const frames: SpriteData[] = [
    createCharacterWalkDown(pal.shirt, pal.skin, pal.pants),
    createCharacterWalkFrame2(pal.shirt, pal.skin, pal.pants),
    createCharacterWalkFrame4(pal.shirt, pal.skin, pal.pants),
    createCharacterTypingFrame1(pal.shirt, pal.skin, pal.pants),
    createCharacterTypingFrame2(pal.shirt, pal.skin, pal.pants),
    createCharacterTypingFrame1(pal.shirt, pal.skin, pal.pants), // read1 = type1
    createCharacterTypingFrame2(pal.shirt, pal.skin, pal.pants), // read2 = type2
  ]

  for (let dirIdx = 0; dirIdx < DIRECTIONS.length; dirIdx++) {
    const rowOffsetY = dirIdx * FRAME_H

    for (let f = 0; f < frames.length; f++) {
      const frame = frames[f]
      const frameOffsetX = f * FRAME_W

      for (let y = 0; y < SPRITE_H; y++) {
        const row = frame[y]
        if (!row) continue
        for (let x = 0; x < FRAME_W; x++) {
          const cell = row[x]
          const idx = (((rowOffsetY + padTop + y) * width) + (frameOffsetX + x)) * 4

          if (!cell || cell === '') {
            // Transparent
            png.data[idx] = 0
            png.data[idx + 1] = 0
            png.data[idx + 2] = 0
            png.data[idx + 3] = 0
          } else {
            const [r, g, b] = hexToRgb(cell)
            png.data[idx] = r
            png.data[idx + 1] = g
            png.data[idx + 2] = b
            png.data[idx + 3] = 0xFF
          }
        }
      }
    }
  }

  return PNG.sync.write(png)
}

// ─────────────────────────────────────────────────────────────────────
// Main
// ─────────────────────────────────────────────────────────────────────

const outDir = path.join(__dirname, '..', 'webview-ui', 'public', 'assets', 'characters')
fs.mkdirSync(outDir, { recursive: true })

for (let i = 0; i < CHARACTER_PALETTES.length; i++) {
  const buffer = buildCharacterPng(i)
  const outPath = path.join(outDir, `char_${i}.png`)
  fs.writeFileSync(outPath, buffer)
  console.log(`✓ Wrote ${outPath} (palette ${i}, ${FRAME_W * FRAMES_PER_ROW}×${FRAME_H * DIRECTIONS.length})`)
}

console.log(`\nGenerated ${CHARACTER_PALETTES.length} character PNGs`)
console.log('\nPNG layout:')
console.log('  112×96 (7 frames × 16px wide, 3 rows × 32px tall)')
console.log('  Row 0: down, Row 1: up, Row 2: right')
console.log('  Sprite data is 24px tall, bottom-aligned in 32px frame (8px padding at top)')
console.log('\nFrame order (per row):')
console.log('  0: walk_1, 1: walk_2, 2: walk_3, 3: type_1, 4: type_2, 5: read_1, 6: read_2')
