name = "mesh-blackroad"
main = "worker.js"
compatibility_date = "2024-12-01"
workers_dev = true

routes = [
  { pattern = "mesh.blackroad.io/*", zone_name = "blackroad.io" }
]

[[kv_namespaces]]
binding = "MESH"
id = "4b6c967fcc1c4d59aedfc46b67de4aea"
