

#LOG_FILE="/root/.acme.sh/acme.sh.log"
#LOG_LEVEL=1

#AUTO_UPGRADE="1"

#NO_TIMESTAMP=1

    
ACCOUNT_EMAIL='amundsonalexa@gmail.com'
UPGRADE_HASH='5d158b164028b240e0710a8d7a0ce4835a0ba1be'
USER_PATH='/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin'
