name               = "blackroad-stats"
main               = "src/index.js"
compatibility_date = "2024-12-01"
account_id         = "848cf0b18d51e0170e0d1537aec3505a"
routes             = [{ pattern = "stats.blackroad.io/*", zone_name = "blackroad.io" }]

[vars]
GITHUB_USER = "blackboxprogramming"
GITEA_URL   = "https://git.blackroad.io"

[[kv_namespaces]]
binding = "STATS_KV"
id      = "5dd4ea96ea5e4dffa3aed1708c7eb340"

[triggers]
crons = ["*/5 * * * *"]
