name = "detour-blackroad"
main = "src/worker.js"
compatibility_date = "2024-01-01"
account_id = "848cf0b18d51e0170e0d1537aec3505a"

[[d1_databases]]
binding = "DB"
database_name = "blackroad-database"
database_id = "b8b0f098-5eb2-4a20-ac8e-d6851699b9e3"

[[routes]]
pattern = "detour.blackroad.io/*"
zone_name = "blackroad.io"
