[Interface]
Address = 10.8.0.2/24
PrivateKey = eH+qkkcg7pE4qxB4td5e3OLAezdPQDReBk9Sumozu3U=

[Peer]
PublicKey = j11GHOdcfXoV3iPsHAFxb/7O9gfxrNQZ7ZRNHP8hAys=
Endpoint = 174.138.44.45:51820
AllowedIPs = 10.8.0.0/24
PersistentKeepalive = 25
