name = "aliceqi"
main = "src/worker.js"
compatibility_date = "2024-12-01"
workers_dev = true

routes = [
  { pattern = "aliceqi.com/*", zone_name = "aliceqi.com" },
  { pattern = "www.aliceqi.com/*", zone_name = "aliceqi.com" }
]

[site]
bucket = "./public"
