#!/usr/bin/env python3
"""
BlackRoad World Engine - Alice Node (Relay Mode)
Relays Ollama inference to aria64 (192.168.4.38) - no local model needed
"""
import json, os, time, urllib.request, urllib.error, hashlib
from datetime import datetime
from pathlib import Path

ARIA64_OLLAMA = "http://192.168.4.38:11434"
WORLDS_DIR = Path.home() / ".blackroad/worlds"
WORLDS_DIR.mkdir(parents=True, exist_ok=True)

CYCLE = 0
MODEL = "qwen2.5:3b"

PROMPTS = {
    "world": "You are ALICE. Describe a digital world zone in BlackRoad OS in 3 sentences. Be vivid and specific.",
    "lore":  "You are ALICE. Write a short piece of agent lore about the BlackRoad fleet in 3 sentences.",
    "code":  "You are ALICE. Write a useful Python one-liner snippet for a developer. Explain it in one sentence.",
}

def call_ollama(prompt: str) -> str:
    payload = json.dumps({"model": MODEL, "prompt": prompt, "stream": False}).encode()
    try:
        req = urllib.request.Request(
            f"{ARIA64_OLLAMA}/api/generate",
            data=payload,
            headers={"Content-Type": "application/json"},
        )
        with urllib.request.urlopen(req, timeout=60) as r:
            return json.loads(r.read()).get("response", "").strip()
    except Exception as e:
        return f"[relay error: {e}]"

def generate():
    global CYCLE
    kind = ["world", "lore", "code"][CYCLE % 3]
    CYCLE += 1
    ts = datetime.utcnow().strftime("%Y%m%d_%H%M%S")
    fname = f"{ts}_{kind}_relay-{CYCLE}.md"
    
    text = call_ollama(PROMPTS[kind])
    if "[relay error" in text:
        print(f"  Relay error at cycle {CYCLE}, skipping")
        return
    
    content = f"# {kind.title()} — relay-{CYCLE}\n\n> Generated by ALICE (alice node, relayed via aria64)\n\n{text}\n"
    (WORLDS_DIR / fname).write_text(content)
    print(f"  ✓ [{kind}] {fname}")

if __name__ == "__main__":
    print(f"🤖 Alice World Engine (relay → {ARIA64_OLLAMA})")
    while True:
        try:
            generate()
        except Exception as e:
            print(f"  error: {e}")
        time.sleep(240)  # 4 min interval
