name = "blackroad-database"
main = "src/index.js"
compatibility_date = "2024-12-01"
account_id = "848cf0b18d51e0170e0d1537aec3505a"
assets = { directory = "./public" }
workers_dev = true

routes = [
  { pattern = "db.blackroad.io", custom_domain = true }
]

[vars]
CORS_ORIGIN = "*"

[[d1_databases]]
binding = "DB"
database_name = "blackroad-database"
database_id = "b8b0f098-5eb2-4a20-ac8e-d6851699b9e3"
