name = "roadpay"
main = "src/index.js"
compatibility_date = "2024-01-01"
account_id = "848cf0b18d51e0170e0d1537aec3505a"

[[d1_databases]]
binding = "DB"
database_name = "tollbooth"
database_id = "e68cf35b-2095-4484-8ee3-6a8d6d9ab42a"
