[gdrive]
type = drive
token = {"access_token":"ya29.a0ATkoCc4YqQDuDUW46gprPyg-hV2wVl1WuZUyOCrb4ywm4g6P_OMX1Z7Bc62irDYmtMvlZT9Jrqfr1nw5b7VPalhp1SUthCW4DdtitfkaXvtgxPxfGo1RcPxCADudmOqDPL7kFa4U4bFxp7LTO67OmcoGU2UKOX6ACj5_Ki3Cso0GmRUhlj1IhVHlhdFvUBIr4modG49bfAaCgYKAU4SARUSFQHGX2MiqCI_bFwdBLgLz0GPBrFTgw0209","token_type":"Bearer","refresh_token":"1//01CXLLNzSa3vMCgYIARAAGAESNwF-L9Ir-HTm8Oodb8lAXpi_Ka_UA0fiCJ8QfHEsQYy7pSaxNWFitAFhVbMFSu36kibz6r-66sA","expiry":"2026-02-23T17:00:35.547463-06:00","expires_in":3599}
team_drive = 

[gdrive-blackroad]
type = drive
token = {"access_token":"ya29.a0Aa7MYiqVG57GgA5LTGcHoMnQhZO7nPW29SDw78ZQrb66w0q5lRf0vUvRXnYKiWn8cuojcQAhp_gWy6DukgL0fXscZqpBIi7Pe6-Zo1ewi15u9fgA464h6r_EsLAxtQuI_EIOpXMLVOI0W6Rpe4MXbCQTS8qdhN-7LR4uEY4XwXQemc92IfC6Xa0sLWAkSV9Z4RKhYkaMBwaCgYKAR4SARYSFQHGX2MibizmF5E0z4F5WDavkWEwDQ0209","token_type":"Bearer","refresh_token":"1//01i8A-k1yCddsCgYIARAAGAESNwF-L9IrLGZLN-nAUOPYTcOpiQ0uU-fciB3Q-pAWB5vA7CPZFZKY7VZfCKt9WcqTl0a6Zm2ep58","expiry":"2026-03-22T08:00:03.711462774-05:00","expires_in":3599}
team_drive = 
scope = 2, 4

