name = "fleet-api"
main = "src/index.js"
compatibility_date = "2024-01-01"
account_id = "848cf0b18d51e0170e0d1537aec3505a"
workers_dev = true

routes = [
  { pattern = "fleet.blackroad.io/*", zone_name = "blackroad.io" }
]

[[kv_namespaces]]
binding = "STATS"
id = "9555ec8a18aa4ff0a7ca9aa2b09cf877"
