CA_EMAIL='amundsonalexa@gmail.com'
CA_EAB_KEY_ID='pY6UyRdEfZgOjX9TN5Ss1w'
CA_EAB_HMAC_KEY='n5w-ReNyIOkEIgqiy-SuKcEKyT1DlVD4MDKyui_ukwJmSdI7jbAiiRkczcc5z0dnvKlPXrWvpsxdfKjg78KIyA'
ACCOUNT_URL='https://acme.zerossl.com/v2/DV90/account/pY6UyRdEfZgOjX9TN5Ss1w'
CA_KEY_HASH='JlCnqqQH7PcJM/gAhgO/s/mhqa5ru6TrxCc7uB7s67Y='
