name = "roundtrip-blackroad"
main = "src/worker.js"
compatibility_date = "2024-09-01"

[[d1_databases]]
binding = "DB"
database_name = "roundtrip"
database_id = "ec4efdfb-a76e-46fb-a821-1278e17e7b90"

[ai]
binding = "AI"

[[kv_namespaces]]
binding = "ROUNDTRIP_KV"
id = "1861124753e742709fbc393fffa6c9ba"

[vars]
MESH_SECRET = "blackroad-mesh-2026"
