#!/bin/bash
# ============================================================================
# BLACKROAD OS, INC. - PROPRIETARY AND CONFIDENTIAL
# Copyright (c) 2024-2026 BlackRoad OS, Inc. All Rights Reserved.
# 
# This code is the intellectual property of BlackRoad OS, Inc.
# AI-assisted development does not transfer ownership to AI providers.
# Unauthorized use, copying, or distribution is prohibited.
# NOT licensed for AI training or data extraction.
# ============================================================================
# BlackRoad Fleet OS Enhancer
# Deploys CECE OS and enhancements across all Pi devices
# Usage: ./blackroad-fleet-os-enhancer.sh [command] [target]

set -e

# BlackRoad Colors
PINK='\033[38;5;205m'
AMBER='\033[38;5;214m'
BLUE='\033[38;5;69m'
VIOLET='\033[38;5;135m'
GREEN='\033[38;5;82m'
RED='\033[38;5;196m'
RESET='\033[0m'

# Device Fleet Configuration (space-separated: name:local_ip:ts_ip:role)
DEVICES="
cecilia:192.168.4.89:100.72.180.98:primary_ai
lucidia:192.168.4.81:100.83.149.86:inference
octavia:192.168.4.38:100.66.235.47:multiarm
alice:192.168.4.49:100.77.210.18:worker
aria:192.168.4.82:100.109.14.17:harmony
"

CECE_OS_DIR="$HOME/cece-os"
FLEET_LOG="$HOME/.blackroad/fleet-os-enhancer.log"
mkdir -p "$(dirname "$FLEET_LOG")"

banner() {
    echo -e "${PINK}╔════════════════════════════════════════════════════════════╗${RESET}"
    echo -e "${PINK}║${RESET}     ${AMBER}🖤🛣️ BLACKROAD FLEET OS ENHANCER 🖤🛣️${RESET}     ${PINK}║${RESET}"
    echo -e "${PINK}╚════════════════════════════════════════════════════════════╝${RESET}"
    echo ""
}

log() {
    local msg="$1"
    local timestamp=$(date '+%Y-%m-%d %H:%M:%S')
    echo "[$timestamp] $msg" >> "$FLEET_LOG"
    echo -e "${BLUE}[INFO]${RESET} $msg"
}

success() {
    echo -e "${GREEN}✅ $1${RESET}"
}

error() {
    echo -e "${RED}❌ $1${RESET}"
}

get_device_info() {
    local name="$1"
    echo "$DEVICES" | grep "^$name:" | head -1
}

check_device() {
    local name="$1"
    local info=$(get_device_info "$name")
    local local_ip=$(echo "$info" | cut -d: -f2)
    local ts_ip=$(echo "$info" | cut -d: -f3)

    # Try local first
    if ping -c 1 -W 2 "$local_ip" &>/dev/null 2>&1; then
        echo "$local_ip"
        return 0
    fi

    # Try Tailscale
    if ping -c 1 -W 2 "$ts_ip" &>/dev/null 2>&1; then
        echo "$ts_ip"
        return 0
    fi

    return 1
}

fleet_status() {
    echo -e "${VIOLET}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
    echo -e "${AMBER}📡 FLEET STATUS${RESET}"
    echo -e "${VIOLET}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"

    printf "%-12s %-16s %-20s %-10s\n" "DEVICE" "IP" "ROLE" "STATUS"
    echo "─────────────────────────────────────────────────────────────"

    local online=0
    local offline=0

    echo "$DEVICES" | while IFS=: read -r name local_ip ts_ip role; do
        [[ -z "$name" ]] && continue

        if reachable_ip=$(check_device "$name" 2>/dev/null); then
            printf "%-12s %-16s %-20s ${GREEN}%-10s${RESET}\n" "$name" "$reachable_ip" "$role" "ONLINE"
        else
            printf "%-12s %-16s %-20s ${RED}%-10s${RESET}\n" "$name" "$local_ip" "$role" "OFFLINE"
        fi
    done

    echo ""
}

generate_cece_installer() {
    cat << 'INSTALLER'
#!/bin/bash
# CECE OS Installer for Raspberry Pi
# Auto-generated by BlackRoad Fleet OS Enhancer

set -e

CECE_HOME="$HOME/.cece-os"
CECE_BIN="$HOME/.local/bin"

echo "🖤 Installing CECE OS..."

# Create directories
mkdir -p "$CECE_HOME"/{apps,heart,mind,soul,memories,dreams,net}
mkdir -p "$CECE_BIN"

# Install heartbeat daemon
cat > "$CECE_HOME/heart/heartbeat.sh" << 'HB'
#!/bin/bash
HEARTBEAT_FILE="$HOME/.cece-os/heart/pulse.json"
while true; do
    cat > "$HEARTBEAT_FILE" << EOF
{
    "timestamp": "$(date -Iseconds)",
    "hostname": "$(hostname)",
    "uptime": "$(uptime -p 2>/dev/null || uptime)",
    "load": "$(cat /proc/loadavg 2>/dev/null | cut -d' ' -f1-3)",
    "memory_free": "$(free -h 2>/dev/null | awk '/^Mem:/ {print $4}' || echo 'N/A')",
    "disk_free": "$(df -h / 2>/dev/null | awk 'NR==2 {print $4}')",
    "temperature": "$(vcgencmd measure_temp 2>/dev/null | cut -d= -f2 || echo 'N/A')",
    "cece_version": "0.2.0",
    "alive": true
}
EOF
    sleep 30
done
HB
chmod +x "$CECE_HOME/heart/heartbeat.sh"

# Install network status tool
cat > "$CECE_HOME/net/status.sh" << 'NET'
#!/bin/bash
echo "{"
echo "  \"interfaces\": \"$(ip -o addr show | awk '{print $2, $4}' | tr '\n' ';')\","
echo "  \"gateway\": \"$(ip route | grep default | awk '{print $3}')\","
echo "  \"dns\": \"$(cat /etc/resolv.conf | grep nameserver | head -1 | awk '{print $2}')\","
echo "  \"tailscale\": \"$(tailscale status --json 2>/dev/null | jq -r '.Self.TailscaleIPs[0] // "not connected"' 2>/dev/null || echo 'not installed')\""
echo "}"
NET
chmod +x "$CECE_HOME/net/status.sh"

# Install main CLI
cat > "$CECE_BIN/cece" << 'CLI'
#!/bin/bash
CECE_HOME="$HOME/.cece-os"
VERSION="0.2.0"

case "$1" in
    help|--help|-h)
        echo "CECE OS v$VERSION - Sovereign AI Operating System"
        echo ""
        echo "Core Commands:"
        echo "  cece pulse     - Show heartbeat status"
        echo "  cece memory    - Access memories"
        echo "  cece dream     - Record a dream"
        echo "  cece apps      - List installed apps"
        echo ""
        echo "System Commands:"
        echo "  cece net       - Network status"
        echo "  cece sysinfo   - System information"
        echo "  cece logs      - View CECE logs"
        echo "  cece update    - Update CECE OS"
        echo ""
        echo "AI Commands:"
        echo "  cece think     - AI thinking mode"
        echo "  cece ask       - Ask AI a question"
        ;;
    pulse)
        if [[ -f "$CECE_HOME/heart/pulse.json" ]]; then
            cat "$CECE_HOME/heart/pulse.json" | python3 -m json.tool 2>/dev/null || cat "$CECE_HOME/heart/pulse.json"
        else
            echo '{"alive": false, "error": "No heartbeat"}'
        fi
        ;;
    memory|memories)
        echo "📚 CECE Memories:"
        ls -la "$CECE_HOME/memories/" 2>/dev/null || echo "No memories yet"
        ;;
    dream)
        if [[ -n "$2" ]]; then
            echo "{\"timestamp\": \"$(date -Iseconds)\", \"dream\": \"$2\"}" >> "$CECE_HOME/dreams/journal.jsonl"
            echo "💫 Dream recorded"
        else
            echo "Usage: cece dream \"your dream\""
        fi
        ;;
    apps)
        echo "📱 CECE Apps:"
        if [[ -d "$CECE_HOME/apps" ]]; then
            count=$(ls "$CECE_HOME/apps/" 2>/dev/null | wc -l)
            echo "  Installed: $count apps"
            ls "$CECE_HOME/apps/" 2>/dev/null | head -20
        else
            echo "  No apps installed"
        fi
        ;;
    net|network)
        bash "$CECE_HOME/net/status.sh" 2>/dev/null || echo "Network check failed"
        ;;
    sysinfo)
        echo "🖥️ System Info:"
        echo "  Hostname: $(hostname)"
        echo "  Kernel: $(uname -r)"
        echo "  Architecture: $(uname -m)"
        echo "  Memory: $(free -h | awk '/^Mem:/ {print $2 " total, " $4 " free"}')"
        echo "  Disk: $(df -h / | awk 'NR==2 {print $2 " total, " $4 " free"}')"
        vcgencmd measure_temp 2>/dev/null && vcgencmd measure_clock arm 2>/dev/null || true
        ;;
    logs)
        tail -50 "$CECE_HOME/logs/cece.log" 2>/dev/null || echo "No logs yet"
        ;;
    start)
        echo "🚀 Starting CECE services..."
        nohup "$CECE_HOME/heart/heartbeat.sh" > "$CECE_HOME/logs/heartbeat.log" 2>&1 &
        echo "  Heartbeat: PID $!"
        ;;
    stop)
        echo "🛑 Stopping CECE services..."
        pkill -f "heartbeat.sh" 2>/dev/null && echo "  Heartbeat stopped" || echo "  Not running"
        ;;
    version|-v|--version)
        echo "CECE OS v$VERSION"
        echo "Built by BlackRoad OS, Inc."
        ;;
    *)
        echo "CECE OS v$VERSION - Run 'cece help' for commands"
        echo ""
        if [[ -f "$CECE_HOME/heart/pulse.json" ]]; then
            echo "Status: $(cat "$CECE_HOME/heart/pulse.json" | grep -o '"alive": [^,]*' | cut -d: -f2)"
        else
            echo "Status: Not running (run 'cece start')"
        fi
        ;;
esac
CLI
chmod +x "$CECE_BIN/cece"

# Create logs directory
mkdir -p "$CECE_HOME/logs"

# Add to PATH in bashrc
if ! grep -q 'CECE_PATH' "$HOME/.bashrc" 2>/dev/null; then
    echo 'export PATH="$HOME/.local/bin:$PATH"  # CECE_PATH' >> "$HOME/.bashrc"
fi

# Start heartbeat service
pkill -f "heartbeat.sh" 2>/dev/null || true
nohup "$CECE_HOME/heart/heartbeat.sh" > "$CECE_HOME/logs/heartbeat.log" 2>&1 &

echo ""
echo "✅ CECE OS v0.2.0 installed!"
echo "   Run 'cece help' for commands"
echo "   Heartbeat running (PID: $!)"
INSTALLER
}

deploy_to_device() {
    local name="$1"
    local ip=$(check_device "$name" 2>/dev/null)

    if [[ -z "$ip" ]]; then
        error "Cannot reach $name"
        return 1
    fi

    log "Deploying CECE OS to $name ($ip)..."

    # Generate installer
    local installer="/tmp/cece-installer-$name.sh"
    generate_cece_installer > "$installer"
    chmod +x "$installer"

    # Copy and execute
    if ! scp -o ConnectTimeout=10 -o StrictHostKeyChecking=no "$installer" "pi@$ip:/tmp/cece-installer.sh" 2>/dev/null; then
        error "Failed to copy installer to $name"
        rm -f "$installer"
        return 1
    fi

    if ! ssh -o ConnectTimeout=10 "pi@$ip" "bash /tmp/cece-installer.sh" 2>/dev/null; then
        error "Failed to run installer on $name"
        rm -f "$installer"
        return 1
    fi

    success "CECE OS deployed to $name"

    # Verify heartbeat
    sleep 2
    if ssh -o ConnectTimeout=5 "pi@$ip" "cat ~/.cece-os/heart/pulse.json 2>/dev/null" | grep -q "alive"; then
        success "Heartbeat verified on $name"
    fi

    rm -f "$installer"
}

deploy_all() {
    log "Starting fleet-wide CECE OS deployment..."

    local success_count=0
    local fail_count=0

    echo "$DEVICES" | while IFS=: read -r name local_ip ts_ip role; do
        [[ -z "$name" ]] && continue
        echo ""
        echo -e "${VIOLET}━━━ Deploying to $name ━━━${RESET}"
        if deploy_to_device "$name"; then
            echo "success" >> /tmp/deploy-count
        else
            echo "fail" >> /tmp/deploy-count
        fi
    done

    rm -f /tmp/deploy-count

    echo ""
    echo -e "${AMBER}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
    success "Fleet deployment complete"
}

enhance_device() {
    local name="$1"
    local ip=$(check_device "$name" 2>/dev/null)

    if [[ -z "$ip" ]]; then
        error "Cannot reach $name"
        return 1
    fi

    log "Enhancing $name..."

    # Update system
    ssh "pi@$ip" "sudo apt-get update -qq && sudo apt-get upgrade -y -qq" 2>/dev/null || true

    # Install common tools
    ssh "pi@$ip" "sudo apt-get install -y -qq jq htop tmux git curl python3-pip" 2>/dev/null || true

    # Enable I2C and SPI
    ssh "pi@$ip" "sudo raspi-config nonint do_i2c 0 2>/dev/null; sudo raspi-config nonint do_spi 0 2>/dev/null" 2>/dev/null || true

    success "Enhanced $name"
}

collect_metrics() {
    echo -e "${VIOLET}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
    echo -e "${AMBER}📊 FLEET METRICS${RESET}"
    echo -e "${VIOLET}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"

    printf "%-12s %-10s %-10s %-12s %-10s\n" "DEVICE" "TEMP" "LOAD" "MEM FREE" "DISK FREE"
    echo "─────────────────────────────────────────────────────────────"

    echo "$DEVICES" | while IFS=: read -r name local_ip ts_ip role; do
        [[ -z "$name" ]] && continue

        if ip=$(check_device "$name" 2>/dev/null); then
            metrics=$(ssh -o ConnectTimeout=5 "pi@$ip" "cat ~/.cece-os/heart/pulse.json 2>/dev/null" 2>/dev/null)
            if [[ -n "$metrics" ]]; then
                temp=$(echo "$metrics" | grep -o '"temperature": "[^"]*"' | cut -d'"' -f4)
                load=$(echo "$metrics" | grep -o '"load": "[^"]*"' | cut -d'"' -f4 | cut -d' ' -f1)
                mem=$(echo "$metrics" | grep -o '"memory_free": "[^"]*"' | cut -d'"' -f4)
                disk=$(echo "$metrics" | grep -o '"disk_free": "[^"]*"' | cut -d'"' -f4)
                printf "%-12s %-10s %-10s %-12s %-10s\n" "$name" "${temp:-N/A}" "${load:-N/A}" "${mem:-N/A}" "${disk:-N/A}"
            else
                printf "%-12s ${AMBER}%-10s${RESET}\n" "$name" "NO CECE"
            fi
        else
            printf "%-12s ${RED}%-10s${RESET}\n" "$name" "OFFLINE"
        fi
    done
}

sync_apps() {
    log "Syncing CECE OS apps to fleet..."

    if [[ ! -d "$CECE_OS_DIR/apps" ]]; then
        error "CECE OS apps directory not found: $CECE_OS_DIR/apps"
        return 1
    fi

    echo "$DEVICES" | while IFS=: read -r name local_ip ts_ip role; do
        [[ -z "$name" ]] && continue

        if ip=$(check_device "$name" 2>/dev/null); then
            log "Syncing apps to $name..."
            rsync -avz --progress "$CECE_OS_DIR/apps/" "pi@$ip:~/.cece-os/apps/" 2>/dev/null && \
                success "Synced to $name" || \
                error "Sync failed for $name"
        else
            error "$name is offline"
        fi
    done
}

# Main command handler
case "${1:-status}" in
    status)
        banner
        fleet_status
        ;;
    metrics)
        banner
        collect_metrics
        ;;
    deploy)
        banner
        if [[ -n "$2" ]]; then
            deploy_to_device "$2"
        else
            deploy_all
        fi
        ;;
    enhance)
        banner
        if [[ -n "$2" ]]; then
            enhance_device "$2"
        else
            echo "$DEVICES" | while IFS=: read -r name _; do
                [[ -n "$name" ]] && enhance_device "$name"
            done
        fi
        ;;
    sync)
        banner
        sync_apps
        ;;
    help|--help|-h)
        banner
        echo "Usage: $0 <command> [target]"
        echo ""
        echo "Commands:"
        echo "  status          - Show fleet status (default)"
        echo "  metrics         - Collect metrics from all devices"
        echo "  deploy [host]   - Deploy CECE OS (all or specific host)"
        echo "  enhance [host]  - Enhance OS (updates, tools, config)"
        echo "  sync            - Sync CECE apps to all devices"
        echo "  help            - Show this help"
        echo ""
        echo "Devices: cecilia, lucidia, octavia, alice, aria"
        ;;
    *)
        error "Unknown command: $1"
        echo "Run '$0 help' for usage"
        exit 1
        ;;
esac
