print_info() {
    info title
    info underline
    info "OS" distro
    info "Host" model
    info "Kernel" kernel
    info "Uptime" uptime
    info "Packages" packages
    info "Shell" shell
    info "Memory" memory
    info "Disk" disk
    info "CPU" cpu
    info "Local IP" local_ip
    info cols
}

# BlackRoad Colors
colors=(208 202 198 163 33 255)
bold="on"
separator=" ◆ "

# ASCII
ascii_distro="auto"
ascii_colors=(208 202 198 163 33 255)
