// Copyright (c) 2025-2026 BlackRoad OS, Inc. All Rights Reserved.
import { Command } from 'commander'
import { logger } from '../../core/logger.js'
import { randomBytes } from 'node:crypto'
import { mkdirSync, writeFileSync, readFileSync, existsSync, appendFileSync } from 'node:fs'
import { join } from 'node:path'
import { homedir } from 'node:os'

function vaultDir(): string {
  const dir = join(homedir(), '.blackroad', 'vault')
  mkdirSync(dir, { recursive: true })
  return dir
}

function auditLogPath(): string {
  const dir = join(homedir(), '.blackroad', 'logs')
  mkdirSync(dir, { recursive: true })
  return join(dir, 'mcp-audit.log')
}

function mcpConfPath(): string {
  return join(homedir(), '.blackroad', 'mcp-bridge.conf')
}

export const mcpCommand = new Command('mcp')
  .description('MCP bridge management')

mcpCommand
  .command('rotate-token')
  .description('Generate and store a new MCP bridge auth token')
  .action(() => {
    const token = randomBytes(32).toString('hex')
    const tokenFile = join(vaultDir(), 'mcp-bridge-token')

    writeFileSync(tokenFile, token, { mode: 0o600 })
    logger.success(`New token written to ${tokenFile}`)

    const confPath = mcpConfPath()
    const confContent = `# MCP Bridge Configuration\n# Auto-generated by br mcp rotate-token\nMCP_BRIDGE_TOKEN=${token}\n`
    writeFileSync(confPath, confContent, { mode: 0o600 })
    logger.success(`Config updated at ${confPath}`)

    const timestamp = new Date().toISOString()
    appendFileSync(auditLogPath(), `${timestamp} | token-rotated | mcp-bridge\n`)
    logger.info('Rotation event logged to audit log')

    logger.warn('Restart the MCP bridge to apply the new token.')
  })

mcpCommand
  .command('status')
  .description('Check MCP bridge token status')
  .action(() => {
    const tokenFile = join(vaultDir(), 'mcp-bridge-token')
    if (existsSync(tokenFile)) {
      const token = readFileSync(tokenFile, 'utf-8').trim()
      logger.success(`Token configured (${token.slice(0, 8)}...${token.slice(-4)})`)
    } else {
      logger.warn('No MCP bridge token found. Run: br mcp rotate-token')
    }

    const confPath = mcpConfPath()
    if (existsSync(confPath)) {
      logger.success(`Config exists at ${confPath}`)
    } else {
      logger.warn('No MCP bridge config found.')
    }
  })
