#!/bin/bash
PINK='\033[38;5;205m'
NC='\033[0m'

case "$1" in
    get)
        python3 ~/.blackroad/config/config_center.py get "$2"
        ;;
    set)
        python3 ~/.blackroad/config/config_center.py set "$2" "$3" "${4:-node}"
        ;;
    show)
        python3 ~/.blackroad/config/config_center.py show
        ;;
    sync)
        python3 ~/.blackroad/config/config_center.py sync
        ;;
    env)
        python3 ~/.blackroad/config/config_center.py env
        ;;
    *)
        echo -e "${PINK}br-config${NC} - Config Center"
        echo "Commands: get [key], set <key> <value> [scope], show, sync, env"
        ;;
esac
