#!/bin/bash
# Build the blackroad-pages worker from website HTML files
# Embeds all 21 product pages + landing pages into a single CF Worker
set -e

WEBSITES="$HOME/blackroad-operator/websites"
OUT="$HOME/blackroad-operator/workers/blackroad-pages/src/index.js"

echo "Building blackroad-pages worker..."

cat > "$OUT" << 'HEADER'
// BlackRoad Pages Worker — serves all product subdomain pages
// Auto-generated by build-worker.sh

const PAGES = {};
HEADER

# Map: hostname → website directory
declare -A HOSTMAP=(
  ["blackroad.io"]="blackroad-io"
  ["social.blackroad.io"]="social"
  ["pay.blackroad.io"]="cashroad"
  ["search.blackroad.io"]="roadview"
  ["tutor.blackroad.io"]="roadwork"
  ["radio.blackroad.io"]="soundroad"
  ["game.blackroad.io"]="genesis"
  ["book.blackroad.io"]="vaultroad"
  ["api.blackroad.io"]="oneway"
  ["work.blackroad.io"]="roadtrip"
  ["roundtrip.blackroad.io"]="roundtrip-hw"
  ["dash.blackroad.io"]="dashboard"
  ["status.blackroad.io"]="status-app"
  ["docs.blackroad.io"]="docs-app"
  ["agents.blackroad.io"]="agent-profile"
  ["video.blackroad.io"]="video"
  # Other root domains
  ["blackroadai.com"]="blackroad-ai"
  ["blackroad.network"]="blackroad-network"
  ["blackroad.systems"]="blackroad-systems"
  ["blackroad.company"]="blackroad-company"
  ["blackroad.me"]="blackroad-me"
  ["blackroadinc.us"]="blackroadinc-us"
  ["blackroadqi.com"]="blackroadqi"
  ["blackroadquantum.com"]="blackroad-quantum"
  ["blackroadquantum.info"]="blackroad-quantum-info"
  ["blackroadquantum.net"]="blackroad-quantum-net"
  ["blackroadquantum.shop"]="blackroad-quantum-shop"
  ["blackroadquantum.store"]="blackroad-quantum-store"
  ["lucidia.earth"]="lucidia-earth"
  ["lucidia.studio"]="lucidia-studio"
  ["lucidiaqi.com"]="lucidiaqi"
  ["roadchain.io"]="roadchain"
  ["roadcoin.io"]="roadcoin"
  ["blackboxprogramming.io"]="blackboxprogramming"
)

# Sub-pages on blackroad.io
declare -A SUBPAGES=(
  ["/pricing"]="pricing"
  ["/ecosystem"]="ecosystem"
  ["/changelog"]="changelog"
  ["/about"]="about"
  ["/leadership"]="leadership"
  ["/onboarding"]="onboarding"
)

count=0

for host in "${!HOSTMAP[@]}"; do
  dir="${HOSTMAP[$host]}"
  html_file="$WEBSITES/$dir/index.html"
  if [ -f "$html_file" ]; then
    # Escape backticks and ${} in the HTML for JS template literal
    escaped=$(sed 's/`/\\`/g; s/\${/\\${/g' "$html_file")
    echo "PAGES[\"$host\"] = \`$escaped\`;" >> "$OUT"
    count=$((count + 1))
    echo "  + $host → $dir"
  fi
done

# Add sub-pages
for path in "${!SUBPAGES[@]}"; do
  dir="${SUBPAGES[$path]}"
  html_file="$WEBSITES/$dir/index.html"
  if [ -f "$html_file" ]; then
    escaped=$(sed 's/`/\\`/g; s/\${/\\${/g' "$html_file")
    echo "PAGES[\"blackroad.io${path}\"] = \`$escaped\`;" >> "$OUT"
    count=$((count + 1))
    echo "  + blackroad.io${path} → $dir"
  fi
done

# Also add sitemap and robots
if [ -f "$WEBSITES/blackroad-io/sitemap.xml" ]; then
  sitemap=$(sed 's/`/\\`/g; s/\${/\\${/g' "$WEBSITES/blackroad-io/sitemap.xml")
  echo "const SITEMAP = \`$sitemap\`;" >> "$OUT"
fi
if [ -f "$WEBSITES/blackroad-io/robots.txt" ]; then
  robots=$(sed 's/`/\\`/g; s/\${/\\${/g' "$WEBSITES/blackroad-io/robots.txt")
  echo "const ROBOTS = \`$robots\`;" >> "$OUT"
fi

cat >> "$OUT" << 'WORKER'

// CORS headers for API
const CORS = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Methods": "GET, POST, OPTIONS",
  "Access-Control-Allow-Headers": "Content-Type",
};

function json(data, status = 200) {
  return new Response(JSON.stringify(data), {
    status,
    headers: { "Content-Type": "application/json", ...CORS },
  });
}

export default {
  async fetch(request, env) {
    const url = new URL(request.url);
    const hostname = url.hostname;
    const path = url.pathname;

    // CORS preflight
    if (request.method === "OPTIONS") {
      return new Response(null, { headers: CORS });
    }

    // === API ENDPOINTS ===

    // Waitlist signup
    if (path === "/api/waitlist" && request.method === "POST") {
      try {
        const body = await request.json();
        const { email, name, role, interests, referral } = body;
        if (!email || !email.includes("@")) return json({ error: "Valid email required" }, 400);

        await env.WAITLIST.prepare(
          "INSERT OR IGNORE INTO waitlist (email, name, role, interests, referral_source) VALUES (?, ?, ?, ?, ?)"
        ).bind(email, name || "", role || "", interests || "", referral || "").run();

        const count = await env.WAITLIST.prepare("SELECT count(*) as cnt FROM waitlist").first();
        return json({ success: true, position: count.cnt, message: "You're on the list." });
      } catch (e) {
        return json({ error: "Already on the list or invalid data" }, 409);
      }
    }

    // Waitlist count
    if (path === "/api/waitlist/count") {
      const count = await env.WAITLIST.prepare("SELECT count(*) as cnt FROM waitlist").first();
      return json({ count: count.cnt });
    }

    // Search API
    if (path === "/api/search" && url.searchParams.get("q")) {
      const q = url.searchParams.get("q");
      const limit = Math.min(parseInt(url.searchParams.get("limit") || "20"), 50);
      try {
        const results = await env.SEARCH.prepare(
          "SELECT url, domain, title, description, category, tags FROM pages WHERE title LIKE ? OR description LIKE ? OR content LIKE ? LIMIT ?"
        ).bind(`%${q}%`, `%${q}%`, `%${q}%`, limit).all();
        return json({ query: q, results: results.results, count: results.results.length });
      } catch (e) {
        return json({ query: q, results: [], count: 0, error: e.message });
      }
    }

    // Analytics pixel
    if (path === "/api/ping") {
      const event = url.searchParams.get("e") || "pageview";
      const ref = request.headers.get("referer") || "";
      const ua = request.headers.get("user-agent") || "";
      const country = request.headers.get("cf-ipcountry") || "";
      try {
        await env.WAITLIST.prepare(
          "INSERT INTO analytics (event, domain, path, referrer, user_agent, ip_country) VALUES (?, ?, ?, ?, ?, ?)"
        ).bind(event, hostname, url.searchParams.get("p") || "/", ref, ua.substring(0, 200), country).run();
      } catch (e) {}
      return new Response("ok", { headers: { ...CORS, "Cache-Control": "no-store" } });
    }

    // Stats endpoint
    if (path === "/api/stats") {
      try {
        const waitlist = await env.WAITLIST.prepare("SELECT count(*) as cnt FROM waitlist").first();
        const pages = await env.SEARCH.prepare("SELECT count(*) as cnt FROM pages").first();
        const views = await env.WAITLIST.prepare("SELECT count(*) as cnt FROM analytics WHERE event = 'pageview'").first();
        return json({
          waitlist: waitlist.cnt,
          indexed_pages: pages.cnt,
          total_views: views.cnt,
          domains: 20,
          subdomains: 16,
          agents: 1000,
          status: "operational",
        });
      } catch (e) {
        return json({ status: "operational", error: e.message });
      }
    }

    // Serve robots.txt
    if (path === "/robots.txt" && typeof ROBOTS !== "undefined") {
      return new Response(ROBOTS, { headers: { "Content-Type": "text/plain", "Cache-Control": "public, max-age=86400" } });
    }

    // Serve sitemap.xml
    if (path === "/sitemap.xml" && typeof SITEMAP !== "undefined") {
      return new Response(SITEMAP, { headers: { "Content-Type": "application/xml", "Cache-Control": "public, max-age=86400" } });
    }

    // Serve IndexNow key verification
    if (path === "/f1a7893bd54145a697f112eefdac579b.txt") {
      return new Response("f1a7893bd54145a697f112eefdac579b", { headers: { "Content-Type": "text/plain" } });
    }

    // Try hostname + path first (for sub-pages like /pricing)
    const subpageKey = hostname + path;
    if (PAGES[subpageKey]) {
      return new Response(PAGES[subpageKey], {
        headers: {
          "Content-Type": "text/html;charset=UTF-8",
          "Cache-Control": "public, max-age=3600",
          "X-Powered-By": "BlackRoad OS",
        },
      });
    }

    // Try hostname only (root page)
    if (PAGES[hostname]) {
      return new Response(PAGES[hostname], {
        headers: {
          "Content-Type": "text/html;charset=UTF-8",
          "Cache-Control": "public, max-age=3600",
          "X-Powered-By": "BlackRoad OS",
        },
      });
    }

    // 404
    return new Response(`<!DOCTYPE html><html><head><title>404 — BlackRoad OS</title><style>body{background:#0a0a0a;color:#f5f5f5;font-family:Inter,sans-serif;display:flex;align-items:center;justify-content:center;min-height:100vh;margin:0}div{text-align:center}h1{font-size:48px;font-weight:700;margin-bottom:8px}p{color:#525252;font-size:14px}a{color:#737373}</style></head><body><div><h1>404</h1><p>Page not found on ${hostname}</p><p><a href="https://blackroad.io">blackroad.io</a></p></div></body></html>`, {
      status: 404,
      headers: { "Content-Type": "text/html;charset=UTF-8" },
    });
  },
};
WORKER

echo ""
echo "Built $count pages into worker"
echo "Output: $OUT"
echo "Size: $(du -sh "$OUT" | awk '{print $1}')"
